function shuffleArray(array) {
    //You take the length of the array ex. [1,2,3,4,5], so 5, and subtract 1 from that since the first number in the array is equal to zero. This means that he range is from 0-4. This decrements every loop until it exits at zero.
    for (i = array.length - 1; i > 0; i--) {
//math function to bring the position of the number at the i position to that position +1 so as to have that number randomized at position 2 the possibility of remaining in the same position, for example.
        var x = Math.floor(Math.random() * (i + 1));
//variable set to the original position of the original array for "backup" purposes.
        var temp = array[i];
//you take the original position's number at i, and move it to the new positin at x generated by the Math.random function. Then you take the number that was in the position x, and set it to the old position i, essentially fliping the positions.
        array[i] = array[x];
        array[x] = temp;
    }
    // return new array after the loop exits at i=0.
    return array;
}
